### ISSUE TITLE
格式校验不支持10月份出生的人

### ISSUE THREAD

**Issue by sliao828** [luopotaotao/IdValidator#1]
reg = regexp.MustCompile("^(\\d{6})(18|19|20)?(\\d{2})(0\\d|11|12)([012]\\d|3[01])(\\d{3})(\\d|X)?$")
是否该改为
reg = regexp.MustCompile("^(\\d{6})(18|19|20)?(\\d{2})(0\\d|10|11|12)([012]\\d|3[01])(\\d{3})(\\d|X)?$")

**Comment by luopotaotao** [comment]
yes you are right!

**Comment by luopotaotao** [comment]
已修改,thank you!
